name: Formatting Validation

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Prettier
        run: npm install --global prettier@latest

      - name: Run Prettier Check
        id: prettier-check
        run: |
          OUTPUT=$(prettier --list-different \
            --config ./.prettierrc \
            --ignore-path ./.prettierignore \
            --no-error-on-unmatched-pattern '**/*.{js,jsx,ts,tsx,json}')

          echo "$OUTPUT"
          echo "PRETTIER_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          if [ -n "$OUTPUT" ]; then
            echo "‚ùå Prettier check failed. Please run prettier locally and commit the changes."
            exit 1
          fi
